baseURL: https://programmercave.com
disablePathToLower: true
languageCode: en-us
title: programmerCave
defaultContentLanguage: en
theme: cayman-hugo-theme

# Google analytics
googleAnalytics: G-LGYYYX4F59

# Syntax highlighting
pygmentsCodefences: true
pygmentsStyle: pygments

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

params:
  # Header text, can be markdown
  project_name: programmerCave
  project_tagline:
  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: 2006-01-02

  facebook_username: "programmercave"
  github_username: "abhiabhi0"
  instagram_username: "programmercave"
  telegram_username: "programmercave"
  twitter_username: "programmercave"
  medium_username: "@programmercave0"
  linkedin_username: "abhishek-singh-thakur-351488147/"
  youtube_username: "UCGpGM7FBgVm7Cmuo6OrUYGQ"
  hackerank_username: "Botman1001"

  # Footer text, can be markdown
  footer:
  # If true, the CSS/JS for Katex math typesetting are enabled
  katex: true

  # Breakpoints
  large_breakpoint: 64em
  medium_breakpoint: 42em

  # Header colors
  header_heading_color: "#fff"
  header_background_color: "#159957"
  header_background_color_secondary: "#155799"

  # Text colors
  section_headings_color: "#159957"
  body_text_color: "#606c71"
  body_link_color: "#1e6bb8"
  blockquote_text_color: "#819198"

  # Code colors
  code_background_color: "#f3f6fa"
  code_text_color: "#567482"

  # Border colors
  border_color: "#dce6f0"
  table_border_color: "#e9ebec"
  hr_border_color: "#eff0f1"

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
    - name: RSS
      url: /index.xml
      weight: 4
