source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll-feed'
gem 'jekyll-tagging'
gem 'jekyll-tagging-related_posts'
gem 'nokogiri'
gem 'rack'
gem 'rspec'
gem 'webrick'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
