source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll-feed'
gem 'jekyll-tagging'
gem 'jekyll-tagging-related_posts'
gem 'nokogiri'
gem 'rack'
gem 'rspec'
gem 'webrick'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'liquid_reading_time', '~> 1.1', '>= 1.1.3'
gem 'jekyll-toc', '~> 0.18.0'
gem 'jekyll-target-blank'